Upgrade to Payload 2 (#214)
* start payload migration

donno why we're getting this error

```console
/Users/gamepress/Documents/GitHub/core/node_modules/payload/dist/admin/assets/images/favicon.svg:1
<svg width="260" height="260" viewBox="0 0 260 260" fill="none" xmlns="http://www.w3.org/2000/svg">
^

SyntaxError: Unexpected token '<'
```

* fix custom

* no longer need nodemon to watch in node18

* this seems to cause build to fail

* Revert "no longer need nodemon to watch in node18"

This reverts commit 5c1335a808d8863a276344346924b97682632fa6.

* Update core.server.ts

* bump payload

* mongoURL moved to payload.config

* style updates

---------

Co-authored-by: Nick Winters <nick@pogseal.com>